FROM python:3.11

WORKDIR /senal

COPY requirements.txt requirements.txt 
COPY ./static ./static 
COPY ./images ./images 
COPY ./templates ./templates 

RUN pip install -r requirements.txt

CMD [ "python", "app.py" ]

